# Generated by Django 4.2.9 on 2026-01-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='group_id',
        ),
    ]
