# Generated by Django 4.2.9 on 2026-01-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_available_for_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_subject',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
