# Generated by Django 4.2.9 on 2026-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_faculty_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
